config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :works

  get '/works' => 'works#index'
  get '/search' => 'works#search'

  resources :users, except: [:index] do
    resources :favorites, except: [:edit, :show, :update]
  end


  resources :sessions, only: [:create]

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'


end

app/models/work.rb
class Article < ActiveRecord::Base

  has_many :comments, :dependent => :destroy

end

app/controllers/works_controller.rb
class WorksController < ApplicationController

  def search
    work = params[:q].gsub(" ", "+")
    response = HTTParty.get(index_api_path "&creator=#{work}&pageSize=60")
    response_hash = response
    @search_query = work
    @search_results = response_hash["Items"]
  end

  def index
    response = HTTParty.get(index_api_path "&creator=#{work}&pageSize=60")
    response_hash = response
    @search_results = response_hash["Items"]
  end

  def show
    @favorite = Favorite.new
    object_id = params[:id].gsub(" ", "+")
    response_hash = HTTParty.get(show_api_path "#{object_id}")
    # response_hash = response
    @search_results = response_hash["Data"]
    @creator_accent_remove = creator_accent_remove
    @work_long_lat = "#{@search_results['Geographies'][0]['LatitudeNumber']},#{@search_results['Geographies'][0]['LongitudeNumber']}"
    # work_location_response = HTTParty.get(geocode_api_path "#{@work_long_lat}")
    # @work_location = work_location_response["results"][2]["address_components"][1]["long_name"]
  end

end

app/views/works/_comment_form.html.erb
<%= form_for [@work, @comment] do |f| %>

  <div class="field">
    <%= f.text_area :body %>
  </div>

  <%= f.hidden_field :walters_id, :value => @search_results["ObjectID"] %>
  <%= f.submit "Submit" %>
<% end %>

app/views/works/_favorite_form.html.erb
<% if signed_in? %>

  <%= form_for [current_user, @favorite] do |f| %>
    <%= f.hidden_field :walters_id, :value => @search_results["ObjectID"] %>
    <%= f.hidden_field :walters_title, :value => @search_results["Title"] %>
    <%= f.hidden_field :walters_image_url, :value => @search_results["Images"][0]["ImageURLs"]["Large"] %>
    <%= f.submit 'Add To Your Collection', class: 'action' %>
  <% end %>

<% else %>

  <p class="action"><%= link_to "Add to Your Collection", signup_path %></p>

<% end %>

app/views/works/_favorite_small_form.html.erb
<% if signed_in? %>

<% else %>

  <p class="action-small"><%= link_to "+", signup_path %></p>

<% end %>

app/views/works/_hero_work.html.erb
<div class="hero--container">
  <% random_results.shuffle.sample(1).each do |work| %>
    <div class="hero--inner">
      <a href="/works/<%= work["ObjectID"] %>"><img class="image--random" src="<%= work["PrimaryImage"]["Raw"] %>" alt="<%= work["Title"] %>" title="<%= work["Title"] %> &ndash; <%= work["Creator"] %>"/></a>
    </div>
    <h2><strong>Random Feature</strong>: <a href="/works/<%= work["ObjectID"] %>"><%= work["Title"] %> &ndash; <%= work["Creator"] %></a></h2>
    <p><%= work["Description"] %>&nbsp;<a href="/works/<%= work["ObjectID"] %>">Learn more&nbsp;&raquo;</a></p>
  <% end %>
</div>

app/views/works/_map.html.erb
<div class="map">
  <h2><%= @search_results["Geographies"][0]["GeographyTerm"] %></h2>
  <iframe
    width="320"
    height="250"
    frameborder="0" style="border:0"
    src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAQC0PETU6apgsLpx-txbiYeXhSIq0PUao&q=<%= @work_long_lat %>&zoom=6">
  </iframe>
  <p>This map details the origin location of the object.</p>
</div>

app/views/works/_work.html.erb
<h1><%= @search_results["Title"] %></h1>
<h2><a href="/search?utf8=✓&q=<%= @search_results['Creators'][0]['ConcatDisplayName'].tr(
"ÀÁÂÃÄÅàáâãäåĀāĂăĄąÇçĆćĈĉĊċČčÐðĎďĐđÈÉÊËèéêëĒēĔĕĖėĘęĚěĜĝĞğĠġĢģĤĥĦħÌÍÎÏìíîïĨĩĪīĬĭĮįİıĴĵĶķĸĹĺĻļĽľĿŀŁłÑñŃńŅņŇňŉŊŋÒÓÔÕÖØòóôõöøŌōŎŏŐőŔŕŖŗŘřŚśŜŝŞşŠšſŢţŤťŦŧÙÚÛÜùúûüŨũŪūŬŭŮůŰűŲųŴŵÝýÿŶŷŸŹźŻżŽž",
"AAAAAAaaaaaaAaAaAaCcCcCcCcCcDdDdDdEEEEeeeeEeEeEeEeEeGgGgGgGgHhHhIIIIiiiiIiIiIiIiIiJjKkkLlLlLlLlLlNnNnNnNnnNnOOOOOOooooooOoOoOoRrRrRrSsSsSsSssTtTtTtUUUUuuuuUuUuUuUuUuUuWwYyyYyYZzZzZz").gsub(" ", "+") %>&commit=Search"><%= @search_results["Creators"][0]["Role"] %>: <%= @search_results["Creators"][0]["ConcatDisplayName"] %></a></h2>

<% if @search_results["Images"][0]["ImageURLs"]["Raw"] %>
<img src="<%= @search_results["Images"][0]["ImageURLs"]["Raw"] %>" alt="">
<% end %>

<% if @search_results["Classification"] %>
<p>Classification: <%= @search_results["Classification"] %></p>
<% end %>

<% if @search_results["Collection"]["Name"] %>
<p>Collection: <%= @search_results["Collection"]["Name"] %></p>
<% end %>

<% if @search_results["DateEndYear"] %>
<p>Completed: <%= @search_results["DateEndYear"] %></p>
<% end %>

<% if @search_results["Period"] %>
<p>Period: <%= @search_results["Period"] %></p>
<% end %>

<% if @search_results["Description"] %>
<p>Description: <%= @search_results["Description"] %></p>
<% end %>

<% if signed_in? %>

  <%= form_tag(work_favorites_path, method: :post) do %>
    <%= submit_tag 'Favorite' %>
  <% end %>

<% end %>

app/views/works/_works_form.html.erb
<%= form_tag("/search", method: "get") do %>
  <%= text_field_tag(:q) %>
  <%= submit_tag "Search", id: 'search', class: 'action' %>
<% end %>

app/views/works/search.html.erb
<h2>Search results for: <%= @search_query.gsub("+", " ") %></h2>
<div class="col-main">
  <% if @search_results %>
  <ul>
    <% @search_results.each do |work| %>
      <li>
        <%= render 'favorite_small_form' %>
        <div class="thumbnail">
        <a href="/works/<%= work["ObjectID"] %>">
          <% if work["PrimaryImage"]["Large"] %>
            <img src="<%= work["PrimaryImage"]["Large"] %>" alt="<%= work["Title"] %>">
          <% else %>
            <img src="http://i.imgur.com/Q4yxumC.png" alt="Image not available">
          <% end %>
        </a>
        </div>
      <a href="/works/<%= work["ObjectID"] %>"><%= work["Title"] %></a>
      <span class="details"><%= work["Creator"] %></span>
      <span class="details"><%= work["Classification"] %>, Completed: <%= work["DateEndYear"] %></span>
    </li>

    <% end %>
  </ul>
  <% else %>
    <p>No results found, please search again.</p>
    <%= render 'works/works_form' %>
  <% end %>
</div>

app/views/works/show.html.erb
<h1><%= @search_results["Title"] %></h1>
<h2><a href="/search?utf8=✓&q=<%= @search_results['Creators'][0]['ConcatDisplayName'].tr(
"ÀÁÂÃÄÅàáâãäåĀāĂăĄąÇçĆćĈĉĊċČčÐðĎďĐđÈÉÊËèéêëĒēĔĕĖėĘęĚěĜĝĞğĠġĢģĤĥĦħÌÍÎÏìíîïĨĩĪīĬĭĮįİıĴĵĶķĸĹĺĻļĽľĿŀŁłÑñŃńŅņŇňŉŊŋÒÓÔÕÖØòóôõöøŌōŎŏŐőŔŕŖŗŘřŚśŜŝŞşŠšſŢţŤťŦŧÙÚÛÜùúûüŨũŪūŬŭŮůŰűŲųŴŵÝýÿŶŷŸŹźŻżŽž",
"AAAAAAaaaaaaAaAaAaCcCcCcCcCcDdDdDdEEEEeeeeEeEeEeEeEeGgGgGgGgHhHhIIIIiiiiIiIiIiIiIiJjKkkLlLlLlLlLlNnNnNnNnnNnOOOOOOooooooOoOoOoRrRrRrSsSsSsSssTtTtTtUUUUuuuuUuUuUuUuUuUuWwYyyYyYZzZzZz").gsub(" ", "+") %>&commit=Search"><%= @search_results["Creators"][0]["Role"] %>: <%= @search_results["Creators"][0]["ConcatDisplayName"] %></a></h2>

<% if @search_results["Images"][0]["ImageURLs"]["Raw"] %>
<img src="<%= @search_results["Images"][0]["ImageURLs"]["Raw"] %>" alt="">
<% end %>

<%= render 'favorite_form' %>

<%= render 'map' %>

<% if @search_results["Classification"] %>
<p>Classification: <%= @search_results["Classification"] %></p>
<% end %>

<% if @search_results["DateEndYear"] %>
<p>Completed: <%= @search_results["DateEndYear"] %></p>
<% end %>

<% if @search_results["Period"] %>
<p>Period: <%= @search_results["Period"] %></p>
<% end %>

<% if @search_results["Description"] %>
<p>Description: <%= @search_results["Description"] %></p>
<% end %>