config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :works

  get '/works' => 'works#index'
  get '/search' => 'works#search'

  resources :users, except: [:index] do
    resources :favorites, except: [:edit, :show, :update]
  end


  resources :sessions, only: [:create]

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'


end

app/models/user.rb
class User < ActiveRecord::Base

  ### Application Specific

  has_many :favorites

  # User can save an item to their personal collection
  def self.save_item
    response = HTTParty.get('')
    users = response_date.map do |line|
      u = User.new
      u.object_id = line['user']['id']
    end
  end

  ### Standard User Model

  # Add handlers to run when creating and saving
  before_create :create_remember_token
  before_save :normalize_fields

  # Validate name:
  validates :name,
    presence: true,
    length: { maximum: 50 }

  # Validate email address:
  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  # Secure password features:
  has_secure_password

  # Create a new remember token for a user:
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  # Hash a token:
  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  # Creates a new session token for the user:
  def create_remember_token
    self.remember_token = User.hash(User.new_remember_token)
  end

  # Normalize fields for consistency:
  def normalize_fields
    self.email.downcase!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  before_action :require_current_user, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to @user
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation
    )
  end

  def require_current_user
    if !current_user?(@user)
      redirect_to root_path
    end
  end
end

app/views/users/_user_favorites.html.erb
<div class="col-main">
  <% if @user.favorites.empty? %>
  <h2>Empty Personal Collection</h2>
    <p>You have not added any items to your personal collection.<br><br>
      Simply find an object you wish to access later and click "add." Then come back here and check it out!</p>
      <%= render 'works/works_form' %>
  <% else %>
      <% @user.favorites.each do |favorite| %>
      <li>
        <div class="thumbnail">
        <a href="/works/<%= favorite.walters_id %>"><img src="<%= favorite.walters_image_url %>"></a>
        </div>
        <a href="/works/<%= favorite.walters_id %>"><%= favorite.walters_title %></a>
      </li>
    <% end %>
  <% end %>
</div>

app/views/users/_user_form.html.erb
<% if @user.errors.any? %>
<b>Errors:</b>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, 'Confirm Password' %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Submit", id: 'submit', class: 'action'  %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit <%= @user.name %></h1>
<%= render "user_form" %>

<hr>

<%= form_for @user, method: 'delete' do |f| %>
  <%= f.submit "Delete", class: 'cancel'  %>
<% end %>

<hr>

<%= link_to "Cancel", @user %>

app/views/users/new.html.erb
<h1>Create a User</h1>
<%= render "user_form" %>
<%= link_to "Already a Member? Sign In", signin_path %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<p><%= @user.email %></p>

<p><%= link_to "Edit", edit_user_path(@user) %></p>

<ul class="profile-show">
<%= render 'user_favorites' %>
</ul>