config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :works

  get '/works' => 'works#index'
  get '/search' => 'works#search'

  resources :users, except: [:index] do
    resources :favorites, except: [:edit, :show, :update]
  end


  resources :sessions, only: [:create]

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'


end

app/views/common/_call_to_action.html.erb
<div class="call">
  <p>
    <% if signed_in? %>
      Welcome back, <%= link_to current_user.name, current_user %>! Did you know you can add objects from <a target="_blank" href="http://thewalters.org/default.aspx">The Walters Museum</a> to a personalized list? <%= link_to "View your saved collection.", current_user %>
    <% else %>
      A virtual visit to Baltimore's <a target="_blank" href="http://thewalters.org/default.aspx">The Walters Museum.</a> Learn more by browsing the collection and favoriting pieces you wish to further study. <%= link_to "Join now!", signup_path %>
    <% end %>
  </p>
</div>

app/views/common/_current_exhibitions.html.erb
<div class="col-main">
  <ul>
    <% @response_hash.each do |exhibit| %>
      <% if exhibit["ExhibEndDate"].gsub("-", "").to_i > Time.now.strftime("%Y%m%d").to_i %>
        <li><%= exhibit["ExhTitle"] %>
        <span class="details"><%= exhibit["Textblock"] %></span></li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/common/_footer.html.erb
<footer>
  <ul>
    <li>MuSM</li>
    <li>2014 &ndash; Matt Rundo (@runtropolis)</li>
  </ul>
  <p>Special thank you to <a target="_blank" href="http://thewalters.org/default.aspx">The Walters Museum</a> for making their API available. All data belongs to the museum.</p>
</footer>

app/views/common/_future_exhibitions.html.erb
<div class="col-main">
  <ul>
    <% @response_hash.each do |exhibit| %>
      <% if exhibit["ExhibBeginDate"].gsub("-", "").to_i < Time.now.strftime("%Y%m%d").to_i %>
        <li><a href="exhibits/<%= exhibit['ExhibitionID']%>"><%= exhibit["ExhTitle"] %></a>
        <span class="details"><%= exhibit["Textblock"] %> <a href="exhibits/<%= exhibit['ExhibitionID']%>">Learn more</a>&nbsp;&raquo;</span></li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/common/_past_exhibitions.html.erb
<div class="col-main">
  <ul>
    <% @response_hash.each do |exhibit| %>
      <% if exhibit["ExhibEndDate"].gsub("-", "").to_i < Time.now.strftime("%Y%m%d").to_i %>
        <li><a href="exhibitions/<%= exhibit['ExhibitionID']%>"><%= exhibit["ExhTitle"] %></a>
        <span class="details"><%= exhibit["Textblock"] %> <a href="exhibits/<%= exhibit['ExhibitionID']%>"></a></span></li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/common/_popular_works.html.erb
<h2>Popular Works</h2>
  <ul>
    <% @favorited_popular.each do |favorite| %>
      <li>
         <img src="<%= favorite["PrimaryImage"]["Raw"] %>" alt="<%= favorite["Title"] %>">
      </li>
    <% end %>
  </ul>

app/views/common/_random_five_works.html.erb
<div>
  <% random_results.shuffle.sample(10).each do |work| %>
    <span class="zoomin image">
      <% if work["PrimaryImage"]["Large"] %>
       <a href="/works/<%= work["ObjectID"] %>"><img class="image--random" src="<%= work["PrimaryImage"]["Large"] %>" alt="<%= work["Title"] %>" title="<%= work["Title"] %> &ndash; <%= work["Creator"] %>"/></a>
      <% else %>
        <img src="../images/not_available.png" alt="">
      <% end %>
    </span>
  <% end %>
</div>

app/views/common/_signout.html.erb
<% if signed_in? %>

  <%= form_for :session, url: signout_path, method: 'delete' do |f| %>
    <ul>
      <li class="nav-user">Signed in as <%= link_to current_user.name, current_user %></li>
      <li class="nav-user"><%= f.submit "Sign out", id: 'signout', class: 'nav-user-cancel' %></li>
    </ul>
  <% end %>

  <% else %>
  <ul>
    <li class="nav-user"><%= link_to "Sign In", signin_path %></li>
    <li class="nav-user"><%= link_to "Sign up", signup_path %></li>
  </ul>

<% end %>